### ISSUE TITLE
'Player' object is not iterable

### ISSUE THREAD

**Issue by mpoqq** [djbrown/hbscorez#1]
Hey, 
all first I want to thank you for your great Job.
I also know that you want to use Redmine (I don't know why), but here it is easier to connect this issue to code.
I think in the code below is a little bug, since the last update. I get follow exception: "_TypeError: 'Player' object is not iterable_".
https://github.com/djbrown/hbscorez/blob/a585b3710c77926b5198baef433192d4c9b4abbc/base/management/commands/import_scores.py#L107

The fix is to remove the call for the first array element.

I came across this when I want to change the Team based "Torjäger" list to display also Player with zero goals. (Maybe this is also a nice Feature =) )

Thanks and have a nice Sunday

**Comment by djbrown** [comment]
Hello @mpoqq :)
thanks for your contribution!

I use Redmine because it allows communication with unregistered, anonymous users.
I think the registration need to contribute on GitHub is a hurdle which most users can't be bothered to take.
It also Redmine allows me to track and manage _all kinds of tasks_, not only source code related issues.

Currently I am working on the project by myself, so I didn't use feature branches yet. That's why the state of the master branch is just a working state (most of the time).
In the future I will create and publish Releases so people can use a stable version of the project.
And maybe I will start using feature branches once the core project is built, but for now im just pusing to master ⏩.

Regarding the bug: I also stumbeled upon the issue you're describing, and already fixed it in commit 49853305 as per your suggestion 👍 
https://github.com/djbrown/hbscorez/blob/49853305e092a348741f00905344cd5623c5a9ce/base/management/commands/import_scores.py#L107

I deliberately filter out Players that have scored zero goals in total Code because I guess some might find it offensive.
In the Team Players View and single Player View all data is displayed in detail.
If you want to see _all_ Players in the League Players View You can just comment out following line:
https://github.com/djbrown/hbscorez/blob/49853305e092a348741f00905344cd5623c5a9ce/base/views.py#L66

Again, huge thanks for checking out the project 🎉
